### ISSUE TITLE
Lost all clips/streamers I've played against

### ISSUE THREAD

**Issue by OhhKennny** [GuardianTheater/guardian-theater#16]
I took a break from d2 for around a month and when I went to check my guardian theater all the streamers I've versed and the clips I've accumulated were gone, I don't know what happened but how do I get them back?

**Comment by chrisfried** [comment]
VODs expire after 60 days for partners, 14 days for affiliates, and (as of September 1st) 7 days for everyone else. As a result, the site only checks the past 60 days of activity when searching for clips.

**Comment by chrisfried** [comment]
<img width="821" alt="Screen Shot 2022-08-18 at 10 39 22 AM" src="https://user-images.githubusercontent.com/422381/185436965-fab48dd1-5bba-427c-863d-b5b8b9f250f2.png">

**Comment by OhhKennny** [comment]
damn that sucks, thanks for informing me
